name: Build .NET Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
      
    - name: Restore dependencies
      run: dotnet restore
      working-directory: bubble/
    
    - name: Make nuget package
      run: dotnet pack
      working-directory: bubble/

#    - name: Build project
#      run: dotnet build --configuration Release --no-restore
#      working-directory: bubble/
